### ISSUE TITLE
unsupported locale setting

### ISSUE THREAD

**Issue by BStalewski** [dahlia/iso4217#10]
Hello, it seems to me that [commit](https://github.com/dahlia/iso4217/commit/ab2ecc000b96223b483c9ee4967404528f124799#diff-45016d89ce5abe492ef28240b9ba581667f0aa7796bd3de93af51ca925bd8891R19) introduced a bug. If locale is not 'C', then simple `from iso4217 import Currency` will fail due to `parse_published` function. It worked in previous version.

Current version:

```
$ pip freeze
iso4217==1.7.20211001

$ python
Python 3.9.6 (default, Jul 22 2021, 16:04:13) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')
'en_US.UTF-8'
>>> from iso4217 import Currency
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bartoszs/.pyenv/versions/test/lib/python3.9/site-packages/iso4217/__init__.py", line 33, in <module>
    __published__ = parse_published(raw_xml.attrib['Pblshd'])
  File "/home/bartoszs/.pyenv/versions/test/lib/python3.9/site-packages/iso4217/__init__.py", line 28, in parse_published
    locale.setlocale(locale.LC_TIME, lc_time)
  File "/home/bartoszs/.pyenv/versions/3.9.6/lib/python3.9/locale.py", line 610, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
>>> locale.setlocale(locale.LC_TIME, 'C')
'C'
>>> from iso4217 import Currency
>>>
```

Previous version:
```
$ pip freeze
iso4217==1.6.20180829

$ python
Python 3.9.6 (default, Jul 22 2021, 16:04:13) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.setlocale(locale.LC_TIME, 'en_US.UTF-8')
'en_US.UTF-8'
>>> from iso4217 import Currency
>>> 
```

The reason of it is that [this line](https://github.com/dahlia/iso4217/commit/ab2ecc000b96223b483c9ee4967404528f124799#diff-45016d89ce5abe492ef28240b9ba581667f0aa7796bd3de93af51ca925bd8891R22) takes only language setting (`en_US`) which is then used in [setlocale](https://github.com/dahlia/iso4217/commit/ab2ecc000b96223b483c9ee4967404528f124799#diff-45016d89ce5abe492ef28240b9ba581667f0aa7796bd3de93af51ca925bd8891R25). Calling `setlocale` would work if it included also encoding part.

The same problem appears to be in [setup.py](https://github.com/dahlia/iso4217/commit/ab2ecc000b96223b483c9ee4967404528f124799#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R99).

**Comment by dahlia** [comment]
Fixed and released a new version: <https://pypi.org/project/iso4217/1.8.20211001/>.
