### ISSUE TITLE
New release to include currency ZWG

### ISSUE THREAD

**Issue by hasier** [dahlia/iso4217#21]
The current version (`1.11.20220401`) does not include the `ZWG` currency, which was only [introduced in April this year](https://en.wikipedia.org/wiki/Zimbabwean_ZiG). It's present in [the most recent XML file](https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml).

Could you generate a new release to include it, please? 🙏

**Comment by dahlia** [comment]
Released [v1.12.20240625](https://pypi.org/project/iso4217/1.12.20240625/).

**Comment by hasier** [comment]
Amazing, thanks for looking into it so quickly! 🙇
