### ISSUE TITLE
pip-compile warns about setuptools included in install_requires

### ISSUE THREAD

**Issue by pbasista** [dahlia/iso4217#5]
Currently, `install_requires` includes the `setuptools` package:

https://github.com/dahlia/iso4217/blob/8455ee01309855b3d1ff8a2db92e9df4d05a0cbd/setup.py#L54

Recent versions of [`pip-tools`](https://github.com/jazzband/pip-tools/), in particular its `pip-compile` tool, report a warning about packages which include `setuptools` in their `install_requires`. It was introduced in this commit: https://github.com/jazzband/pip-tools/commit/766cef063856e2f235225d9fa8b45ffcc68ef975 which was first released with `pip-tools` version [3.8.0](https://github.com/jazzband/pip-tools/tree/3.8.0).

The warning has a form of commented-out lines at the end of the generated `requirements.txt` file:

```
# The following packages are considered to be unsafe in a requirements file:
# setuptools==41.0.1        # via iso4217
```

If I understand correctly, the reason for including this warning is to clearly mark the difference between packages which are required only during the *installation* (i.e. `setuptools` in most cases) and packages, which are required during the regular usage.

Since `iso4217` does not use `setuptools` anywhere except for its `setup.py`:

https://github.com/dahlia/iso4217/blob/8455ee01309855b3d1ff8a2db92e9df4d05a0cbd/setup.py#L15

I think that it may be reasonable to remove it from `install_requires`.

**Comment by dahlia** [comment]
That *setuptools* dependency was added because [`pkg_resources`][1] package (that *setuptools* provides)  is used by *iso4217/\_\_init\_\_.py* file:

https://github.com/dahlia/iso4217/blob/8455ee01309855b3d1ff8a2db92e9df4d05a0cbd/iso4217/__init__.py#L12

[1]: https://setuptools.readthedocs.io/en/latest/pkg_resources.html

**Comment by pbasista** [comment]
I see. I am sorry, I was not aware of that and I did not examine the git history properly.

I am not sure what role does [`resource_string`](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access) play exactly, but is it perhaps possible to load `table.xml` without using it and therefore remove the dependency on `pkg_resources` during the package's regular usage?

**Comment by dahlia** [comment]
The concept of “resources” and its API provide a universal way to deal with resource files embedded in a package even if it's installed as a zipped container (e.g., *.egg* or *.whl*) on a system.  Although it would work well if we replace `pkg_resources.resource_string()` with a straight-forward `open(…).read()`, AFAIK it could not work on some circumstances…

Is there any way to suppress to that warning?

**Comment by pbasista** [comment]
Ok, I see.

I am not sure if suppressing the warning is the reasonable action to take because its content is actually relevant. If the `pkg_resources` package is necessary for regular usage of `iso4217`, then I think that it is fair to keep the warning.

Maybe it is possible to use a different (but still standardized) library for the same purpose. I have noticed that e.g. `pytest` has [recently](https://github.com/pytest-dev/pytest/commit/13f02af97d676bdf7143aa1834c8898fbf753d87) started using [`importlib_metadata`](https://gitlab.com/python-devs/importlib_metadata) package instead of `pkg_resources`. It seems to be a backport of [importlib.metadata](https://docs.python.org/3.8/library/importlib.metadata.html) in standard library of Python 3.8. Perhaps it also has the functionality needed by `iso4217`.

**Comment by dahlia** [comment]
The [`importlib.resources`][1] module in the standard library and its backport package [importlib-resources] seem the perfect replacement for setuptools' `pkg_resources`.  I'm going to work on this in my spare time, but I can't guarantee when it would be shipped.  If you or someone send a patch to replace `pkg_resources` with `importlib.resources` I would review it as soon as I possible.

[1]: https://docs.python.org/3.8/library/importlib.html#module-importlib.resources
[importlib-resources]: https://importlib-resources.readthedocs.io/

**Comment by dahlia** [comment]
Now it does not depend on setuptools.  See also the latest version: <https://pypi.org/project/iso4217/1.7.20211001/>.
